"""
MCP Server Factory

Generates deployable MCP servers from TeamDefinition specifications.
Each team becomes a standalone MCP server with all agents exposed as tools.
"""

import logging
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime
from core.team_registry import TeamDefinition, TeamRegistry
from core.agent_registry import AgentRegistry, AgentRegistryEntry
from core.mcp_tool_generator import MCPToolGenerator

logger = logging.getLogger(__name__)


class MCPServerFactory:
    """
    Factory for generating MCP servers from team definitions.

    Creates fully functional, deployable MCP server Python files that:
    - Import necessary dependencies
    - Initialize all team member agents
    - Register MCP tools for each agent
    - Provide stdio server implementation
    - Include logging and error handling
    """

    def __init__(
        self,
        agent_registry: AgentRegistry,
        team_registry: TeamRegistry
    ):
        """
        Initialize factory.

        Args:
            agent_registry: Agent registry instance
            team_registry: Team registry instance
        """
        self.agent_registry = agent_registry
        self.team_registry = team_registry
        self.tool_generator = MCPToolGenerator()

    def generate_server(
        self,
        team_id: str,
        output_dir: str = "mcp_servers"
    ) -> Path:
        """
        Generate MCP server for a team.

        Args:
            team_id: Team ID
            output_dir: Output directory for server file

        Returns:
            Path to generated server file
        """
        team = self.team_registry.get_team(team_id)
        if not team:
            raise ValueError(f"Team not found: {team_id}")

        # Get all team members with their agent details
        members = self.team_registry.get_team_members_from_registry(
            team_id, self.agent_registry
        )

        if not members:
            raise ValueError(f"No valid team members found for team: {team.name}")

        # Generate server code
        server_code = self._generate_server_code(team, members)

        # Write to file
        output_path = Path(output_dir) / f"{team.mcp_server_name}.py"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w') as f:
            f.write(server_code)

        logger.info(f"Generated MCP server: {output_path}")

        # Record deployment
        self.team_registry.record_deployment(team_id)

        return output_path

    def _generate_server_code(
        self,
        team: TeamDefinition,
        members: List[tuple]
    ) -> str:
        """
        Generate complete server Python code.

        Args:
            team: Team definition
            members: List of (TeamMemberRole, AgentRegistryEntry) tuples

        Returns:
            Python code as string
        """
        # Extract agents from members tuples
        agents = [agent for _, agent in members]

        # Generate imports
        imports = self._generate_imports(team, agents)

        # Generate tool definitions
        tools_code = self._generate_tools_code(team, members)

        # Generate handlers
        handlers_code = self._generate_handlers_code(team, members)

        # Generate main function
        main_code = self._generate_main_code(team)

        # Combine all parts
        server_code = f'''#!/usr/bin/env python3
"""
{team.name} MCP Server

Generated by AgentForge MCP Server Factory
Team ID: {team.id}
Generated: {datetime.now().isoformat()}

Description:
{team.description}

Team Members:
{self._format_team_members_list(members)}

Orchestration: {team.orchestration_type.value}
"""

{imports}

{tools_code}

{handlers_code}

{main_code}

if __name__ == "__main__":
    asyncio.run(main())
'''

        return server_code

    def _generate_imports(
        self,
        team: TeamDefinition,
        agents: List[AgentRegistryEntry]
    ) -> str:
        """Generate import statements"""
        imports = '''import asyncio
import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List

from mcp.server import Server
from mcp.types import Tool, TextContent
from mcp.server.stdio import stdio_server

# Add parent directory for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.agent_registry import AgentRegistry
from core.mcp_tool_generator import MCPToolGenerator

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(f'mcp_servers/{team.mcp_server_name}.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)
'''

        # Add agent-specific imports
        unique_sources = {agent.source for agent in agents}
        if any(source.value == "letta_import" for source in unique_sources):
            imports += "\nfrom agentfile import load_agent"

        return imports

    def _generate_tools_code(
        self,
        team: TeamDefinition,
        members: List[tuple]
    ) -> str:
        """Generate TOOLS list definition"""
        agents = [agent for _, agent in members]

        code = "\n# Define MCP Tools\nTOOLS = [\n"

        # Generate team coordinator tool if enabled
        if team.expose_team_coordinator:
            code += f'''    # Team Coordinator Tool
    Tool(
        name="{team.mcp_tools_prefix}_team",
        description="""{team.description}

        **Orchestration:** {team.orchestration_type.value}
        **Team Size:** {len(members)} agents

        Delegates tasks to appropriate team members and coordinates responses.""",
        inputSchema={{
            "type": "object",
            "properties": {{
                "task": {{"type": "string", "description": "Task for the team"}},
                "context": {{"type": "string", "description": "Additional context"}},
                "orchestration_mode": {{
                    "type": "string",
                    "enum": ["auto", "sequential", "parallel"],
                    "default": "auto"
                }}
            }},
            "required": ["task"]
        }}
    ),

'''

        # Generate individual agent tools
        if team.expose_individual_agents:
            code += "    # Individual Agent Tools\n"
            for member_role, agent in members:
                tool_name = self.tool_generator.generate_tool_name(
                    agent, team.mcp_tools_prefix
                )
                description = self.tool_generator.generate_tool_description(agent)
                input_schema = self.tool_generator.generate_input_schema(agent)

                # Format the tool definition
                code += f'''    Tool(
        name="{tool_name}",
        description="""{description}""",
        inputSchema={json.dumps(input_schema, indent=12)[:-1] + "    }"}
    ),
'''

        code += "]\n"
        return code

    def _generate_handlers_code(
        self,
        team: TeamDefinition,
        members: List[tuple]
    ) -> str:
        """Generate handler functions"""
        code = "\n# Handler Functions\n"

        # Team coordinator handler
        if team.expose_team_coordinator:
            code += f'''
async def handle_team_coordinator(arguments: Dict[str, Any]) -> str:
    """Handle team coordination requests"""
    logger.info(f"Team coordinator invoked: {{arguments.get('task')}}")

    try:
        task = arguments.get("task")
        context = arguments.get("context", "")
        mode = arguments.get("orchestration_mode", "auto")

        # Load agent registry
        agent_registry = AgentRegistry()
        tool_gen = MCPToolGenerator()

        # Get team member IDs
        team_agent_ids = {json.dumps([member_role.agent_id for member_role, _ in members])}

        # Coordinate based on orchestration mode
        if mode == "parallel":
            # Invoke all agents in parallel
            tasks = []
            for agent_id in team_agent_ids:
                agent = agent_registry.get_agent(agent_id)
                if agent:
                    tasks.append(tool_gen.invoke_agent(agent, arguments))

            results = await asyncio.gather(*tasks)
            response = {{
                "status": "success",
                "orchestration": "parallel",
                "results": [json.loads(r) for r in results]
            }}

        else:  # sequential or auto
            results = []
            for agent_id in team_agent_ids:
                agent = agent_registry.get_agent(agent_id)
                if agent:
                    result = await tool_gen.invoke_agent(agent, arguments)
                    results.append(json.loads(result))

            response = {{
                "status": "success",
                "orchestration": "sequential",
                "results": results
            }}

        return json.dumps(response, indent=2)

    except Exception as e:
        logger.error(f"Error in team coordinator: {{e}}", exc_info=True)
        return json.dumps({{"status": "error", "error": str(e)}})

'''

        # Individual agent handlers
        if team.expose_individual_agents:
            code += '''
async def handle_agent_tool(agent_id: str, arguments: Dict[str, Any]) -> str:
    """Handle individual agent tool calls"""
    try:
        agent_registry = AgentRegistry()
        tool_gen = MCPToolGenerator()

        agent = agent_registry.get_agent(agent_id)
        if not agent:
            return json.dumps({"status": "error", "error": f"Agent not found: {agent_id}"})

        result = await tool_gen.invoke_agent(agent, arguments)
        return result

    except Exception as e:
        logger.error(f"Error invoking agent {agent_id}: {e}", exc_info=True)
        return json.dumps({"status": "error", "error": str(e)})

'''

        return code

    def _generate_main_code(self, team: TeamDefinition) -> str:
        """Generate main function"""
        members_map = {
            f'"{member_role.agent_id}"'
            for member_role, _ in self.team_registry.get_team_members_from_registry(
                team.id, self.agent_registry
            )
        }

        return f'''
# Agent ID mapping for routing
AGENT_ID_MAP = {{
{chr(10).join(f"    {agent_id}: {agent_id}," for agent_id in members_map)}
}}


async def main():
    """Run the {team.name} MCP Server"""

    logger.info("Starting {team.name} MCP Server...")

    # Create server
    server = Server("{team.mcp_server_name}")

    @server.list_tools()
    async def list_tools() -> List[Tool]:
        """List available tools"""
        logger.debug("Listing available tools")
        return TOOLS

    @server.call_tool()
    async def call_tool(name: str, arguments: dict) -> List[TextContent]:
        """Handle tool calls"""
        logger.info(f"Tool called: {{name}}")
        logger.debug(f"Arguments: {{arguments}}")

        try:
            # Route to appropriate handler
            if name == "{team.mcp_tools_prefix}_team":
                result = await handle_team_coordinator(arguments)
            else:
                # Extract agent ID from tool name
                # Format: prefix__agent_name
                parts = name.split("__")
                if len(parts) == 2:
                    # Look up agent by name
                    agent_registry = AgentRegistry()
                    matching_agents = agent_registry.find_agents(name=parts[1])
                    if matching_agents:
                        agent_id = matching_agents[0].id
                        result = await handle_agent_tool(agent_id, arguments)
                    else:
                        result = json.dumps({{"status": "error", "error": f"Unknown agent: {{parts[1]}"}})
                else:
                    result = json.dumps({{"status": "error", "error": f"Unknown tool: {{name}}"}})

            return [TextContent(type="text", text=result)]

        except Exception as e:
            logger.error(f"Error in tool call {{name}}: {{e}}", exc_info=True)
            error_response = json.dumps({{
                "status": "error",
                "error": str(e),
                "tool": name
            }}, indent=2)
            return [TextContent(type="text", text=error_response)]

    # Run server with stdio transport
    logger.info("MCP Server ready on stdio...")
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())
'''

    def _format_team_members_list(self, members: List[tuple]) -> str:
        """Format team members list for documentation"""
        lines = []
        for member_role, agent in members:
            coordinator_marker = " (Coordinator)" if member_role.is_coordinator else ""
            lines.append(f"  - {agent.name} ({agent.role}){coordinator_marker}")
        return "\n".join(lines)
